import numpy as np                                                                                                  
output_torch_0 = np.load("output_0.npy")                                                                            
output_torch_1 = np.load("output_1.npy")                                                                            
output_torch_2 = np.load("output_2.npy")                                                                            
output_paddle_0 = np.load("output_0_conv2d_139.tmp_1.npy")                                                          
output_paddle_1 = np.load("output_1_conv2d_140.tmp_1.npy")                                                          
output_paddle_2 = np.load("output_2_conv2d_141.tmp_1.npy")                                                          
output_paddle_0_reshape = output_paddle_0.reshape((3,80,80,85))                                                     
output_paddle_1_reshape = output_paddle_1.reshape((3,40,40,85))                                                     
output_paddle_2_reshape = output_paddle_2.reshape((3,20,20,85))                                                     
output_paddle_0_expand = np.expand_dims(output_paddle_0_reshape, axis=0)                                            
output_paddle_1_expand = np.expand_dims(output_paddle_1_reshape, axis=0)                                            
output_paddle_2_expand = np.expand_dims(output_paddle_2_reshape, axis=0)                                            
print(np.max(abs(output_torch_0 - output_paddle_0_expand)))                                                         
print(np.max(abs(output_torch_1 - output_paddle_1_expand)))                                                         
print(np.max(abs(output_torch_2 - output_paddle_2_expand)))
